version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/my-symfony-project
    volumes:
      - ./:/var/www/my-symfony-project
    entrypoint: >
      bash -c "curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && exec php-fpm"
    networks:
      - symfony_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/my-symfony-project
    networks:
      - symfony_network
    depends_on:
      - php

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: symfony_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
